/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alvaro.llano.interfazpleicula;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Element;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import conexionDB.Conectar;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Font;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.Document;

/**
 *
 * @author Alvaro Llano
 */
public class RegistrarGenero extends javax.swing.JInternalFrame {

    
    //----------------------------------------------------------//
    Connection coneccionsql;
    Statement sentenciasql;
    DefaultTableModel modelo_tabla;
    //----------------------------------------------------------//  
    
    /**
     * Creates new form CargarGenero
     */
    public RegistrarGenero() {
        initComponents();
        TextPrompt placeholder1 = new TextPrompt("Ingrese el nombre del genero", nombre_genero);
              
        coneccionsql = Conectar.getConnection();
        
        LlenarTabla();
        
        BotonBorrar.setEnabled(false);
        BotonEditar.setEnabled(false);
    }
    
    
    
        void LlenarTabla() {
        try {
            //encabezados de la tabla
            String[] titulos = {"ID", "Genero"};
            String stsql = "select * from genero WHERE status <> 0";
            modelo_tabla = new DefaultTableModel(null, titulos);
            sentenciasql = coneccionsql.createStatement();
            ResultSet rs = sentenciasql.executeQuery(stsql);

            //arreglo fila, para almacenar registros
            String[] fila = new String[2];
            
            //while para insertar registros en la tabla
            
            while (rs.next()) {
                fila[0] = rs.getString("id_genero");
                fila[1] = rs.getString("nombre_genero");
                
                modelo_tabla.addRow(fila);
            }

            //agrego el default model
            TablaPersonas.setModel(modelo_tabla);

            //definir el ancho de las columnas
            int[] anchos = {25, 100};
            for (int i = 0; i < TablaPersonas.getColumnCount(); i++) {
                TablaPersonas.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
            }

            //escondemos la columna id en la tabla (finalidad estetica)
            //TablaPersonas.getColumnModel().getColumn(0).setMinWidth(0);
            //TablaPersonas.getColumnModel().getColumn(0).setMaxWidth(0);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaPersonas = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nombre_genero = new javax.swing.JTextField();
        BotonGuardar = new javax.swing.JButton();
        BotonEditar = new javax.swing.JButton();
        BotonBorrar = new javax.swing.JButton();
        CampoID = new javax.swing.JTextField();
        btnPDF = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        TablaPersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaPersonas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaPersonasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaPersonas);

        jPanel1.setBackground(new java.awt.Color(227, 234, 248));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(29, 43, 105));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTAR GENERO");

        nombre_genero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre_generoActionPerformed(evt);
            }
        });

        BotonGuardar.setBackground(new java.awt.Color(0, 255, 51));
        BotonGuardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BotonGuardar.setForeground(new java.awt.Color(255, 255, 255));
        BotonGuardar.setText("GUARDAR");
        BotonGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonGuardarMouseClicked(evt);
            }
        });
        BotonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardarActionPerformed(evt);
            }
        });

        BotonEditar.setBackground(new java.awt.Color(102, 102, 102));
        BotonEditar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BotonEditar.setForeground(new java.awt.Color(255, 255, 255));
        BotonEditar.setText("EDITAR");
        BotonEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonEditarMouseClicked(evt);
            }
        });
        BotonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEditarActionPerformed(evt);
            }
        });

        BotonBorrar.setBackground(new java.awt.Color(255, 0, 0));
        BotonBorrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BotonBorrar.setForeground(new java.awt.Color(255, 255, 255));
        BotonBorrar.setText("BORRAR");
        BotonBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonBorrarMouseClicked(evt);
            }
        });
        BotonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBorrarActionPerformed(evt);
            }
        });

        CampoID.setEditable(false);
        CampoID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BotonEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nombre_genero)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nombre_genero, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(BotonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(BotonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CampoID, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 35, Short.MAX_VALUE))
        );

        btnPDF.setBackground(new java.awt.Color(227, 234, 248));
        btnPDF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPDF.setText("Generar PDF");
        btnPDF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPDFMouseClicked(evt);
            }
        });
        btnPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TablaPersonasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaPersonasMouseClicked
        
        if (evt.getButton() == 1) {
            
            int fila = TablaPersonas.getSelectedRow();
            try {
                String stsql = "select * from genero where id_genero = " + TablaPersonas.getValueAt(fila, 0);
                sentenciasql = coneccionsql.createStatement();
                ResultSet rs = sentenciasql.executeQuery(stsql);
                rs.next();

                CampoID.setText(rs.getString("id_genero"));
                nombre_genero.setText(rs.getString("nombre_genero"));
                
                BotonBorrar.setEnabled(true);
                BotonEditar.setEnabled(true);
                BotonGuardar.setEnabled(false);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
            }
        }  
        
        
    }//GEN-LAST:event_TablaPersonasMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void BotonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonEditarActionPerformed

    private void BotonEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonEditarMouseClicked
        try {
            String id = CampoID.getText();
            String nombregenero = nombre_genero.getText();

            //Guardar en la base de datos
            String stactualizar = "update genero set nombre_genero=? where id_genero=?";
            PreparedStatement ps = coneccionsql.prepareStatement(stactualizar);
            ps.setString(1, nombregenero);
            ps.setString(2, id);
            int n = ps.executeUpdate();
            if (n > 0) {

                //limpiar formulario
                CampoID.setText("");
                nombre_genero.setText(""); //AL GUARDAR ESTE METODO VACIA EL CAMPO PARA INGRESAR UN NUEVO DATO

                //reiniciar el estado de los botones
                BotonGuardar.setEnabled(true);
                BotonEditar.setEnabled(false);
                BotonBorrar.setEnabled(false);

                LlenarTabla();
                JOptionPane.showMessageDialog(this, "Se actualizo correctamente");
            } else {
                JOptionPane.showMessageDialog(this, "Error al actualizar");
            }
            ps.close();

        } catch (Exception e) {
            System.err.println(e);
        }
    }//GEN-LAST:event_BotonEditarMouseClicked

    private void CampoIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoIDActionPerformed

    private void BotonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBorrarActionPerformed

    }//GEN-LAST:event_BotonBorrarActionPerformed

    private void BotonBorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonBorrarMouseClicked
        try {
            String id = CampoID.getText();
            // int status = 0;

            //Borrar registro en la base de datos
            String stborrar = "UPDATE genero SET status = 0 WHERE id_genero =" + id;
            PreparedStatement ps = coneccionsql.prepareStatement(stborrar);

            // ps.setInt(1, status);

            int n = ps.executeUpdate();
            if (n > 0) {
                JOptionPane.showMessageDialog(this, "Se borro correctamente");
            } else {
                JOptionPane.showMessageDialog(this, "Error al borrar");
            }
            ps.close();

            LlenarTabla();

            //limpiar formulario
            CampoID.setText("");
            nombre_genero.setText(""); //AL GUARDAR ESTE METODO VACIA EL CAMPO PARA INGRESAR UN NUEVO DATO

            //Reiniciar el estado de los botones
            BotonGuardar.setEnabled(true);
            BotonBorrar.setEnabled(false);
            BotonEditar.setEnabled(false);

        } catch (Exception e) {
            System.err.println(e);
        }
    }//GEN-LAST:event_BotonBorrarMouseClicked

    private void BotonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonGuardarActionPerformed

    private void BotonGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonGuardarMouseClicked
        try {
            String nombregenero = nombre_genero.getText();

            String sqlguardar = "insert into genero (nombre_genero) values (?)";
            PreparedStatement ps = coneccionsql.prepareStatement(sqlguardar);

            ps.setString(1, nombregenero);

            int n = ps.executeUpdate();
            if (n > 0) {
                nombre_genero.setText(""); //AL GUARDAR ESTE METODO VACIA EL CAMPO PARA INGRESAR UN NUEVO DATO
                JOptionPane.showMessageDialog(this, "Se guardó correctamente");
                LlenarTabla();

            } else {
                JOptionPane.showMessageDialog(this, "Error al guardar");
            }
            //SE CIERRA LA CONEXION CON LA BASE DE DATOS
            ps.close();
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(rootPane, "Error: No se pudo registrar el genero!");
        }

    }//GEN-LAST:event_BotonGuardarMouseClicked

    private void nombre_generoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre_generoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombre_generoActionPerformed

    private void btnPDFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPDFMouseClicked
        try {
            //Buscar la carpeta temporar del sistema operativo
            //Path carpetaTemporal = Files.createTempDirectory(null);
            String carpetaTemporal = "C:\\reportes/";

            //Generar un nombre aleatorio para el PDF
            UUID uuid = UUID.randomUUID();
            String nombreAleatorio = uuid.toString() + ".pdf";

            //Generar el PDF el disco usando los datos de la tabla
            com.itextpdf.text.Document doc = new com.itextpdf.text.Document();
            PdfWriter.getInstance(doc, new FileOutputStream(carpetaTemporal + nombreAleatorio));
            doc.open();
            PdfPTable pdfTable = new PdfPTable(TablaPersonas.getColumnCount());

            //Agregamos el titulo
            Paragraph titulo = new Paragraph("Listado de Peliculas",
                FontFactory.getFont("arial", // fuente
                    20, // tamaño
                    Font.BOLD, // estilo
                    BaseColor.BLUE));               // color
            titulo.setLeading(1, 1);
            titulo.setAlignment(Element.ALIGN_CENTER);
            doc.add(titulo);

            doc.add(new Paragraph(" "));

            //Cabeceras de la tabla
            for (int i = 0; i < TablaPersonas.getColumnCount(); i++) {
                pdfTable.addCell(TablaPersonas.getColumnName(i));
            }
            //Extraer los datos de cada fila del Jtable e insertar en el PDF
            for (int rows = 0; rows < TablaPersonas.getRowCount(); rows++) {
                for (int cols = 0; cols < TablaPersonas.getColumnCount(); cols++) {
                    pdfTable.addCell(TablaPersonas.getModel().getValueAt(rows, cols).toString());
                }
            }
            doc.add(pdfTable);
            doc.close();

            //Abrimos el archivo generado en el disco con el programa predeterminado
            // del sistema operativo, es quivalente a darle doble click
            File myFile = new File(carpetaTemporal + nombreAleatorio);
            Desktop.getDesktop().open(myFile);

        } catch (Exception e) {
            System.err.println("Error: " + e);
        }
    }//GEN-LAST:event_btnPDFMouseClicked

    private void btnPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPDFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPDFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonBorrar;
    private javax.swing.JButton BotonEditar;
    private javax.swing.JButton BotonGuardar;
    private javax.swing.JTextField CampoID;
    private javax.swing.JTable TablaPersonas;
    private javax.swing.JButton btnPDF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombre_genero;
    // End of variables declaration//GEN-END:variables
}
