/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alvaro.llano.interfazpleicula;

import java.awt.Dimension;
import javax.swing.ImageIcon;

/**
 *
 * @author Alvaro Llano
 */
public class vistaPrincipal extends javax.swing.JFrame {
    
    ImageIcon iconobtn = new ImageIcon("src/main/java/imagenes/movies.png");

    /**
     * Creates new form vistaPrincipal
     */
    public vistaPrincipal() {
        initComponents();
        
        Login login = new Login();
        
        // centrar internal frame
        login.setLocation((escritorio.getWidth() - login.getWidth()) / 2, (escritorio.getHeight() - login.getHeight()) / 2);
        
        //iconos
        escritorio.setIcon(iconobtn);
        escritorio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
       // new vistaCargarPeliculas().setVisible(true);
       
       // Se agrega el login dentro del escitorio
        escritorio.add(login);
        login.setVisible(true);
        navbar.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        ventanaPrincipal = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        escritorio = new javax.swing.JLabel();
        navbar = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        opCargarPeliculas = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        registrar_genero = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        cargar_usuarios = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 0));

        jPanel1.setBackground(new java.awt.Color(227, 234, 248));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 968, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
        );

        ventanaPrincipal.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout ventanaPrincipalLayout = new javax.swing.GroupLayout(ventanaPrincipal);
        ventanaPrincipal.setLayout(ventanaPrincipalLayout);
        ventanaPrincipalLayout.setHorizontalGroup(
            ventanaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ventanaPrincipalLayout.setVerticalGroup(
            ventanaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        navbar.setBackground(new java.awt.Color(227, 234, 248));

        jMenu2.setText("PELICULAS");

        opCargarPeliculas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        opCargarPeliculas.setText("Cargar Peliculas");
        opCargarPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opCargarPeliculasActionPerformed(evt);
            }
        });
        jMenu2.add(opCargarPeliculas);

        navbar.add(jMenu2);

        jMenu1.setText("GENEROS");

        registrar_genero.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        registrar_genero.setText("Registrar Genero");
        registrar_genero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrar_generoActionPerformed(evt);
            }
        });
        jMenu1.add(registrar_genero);

        navbar.add(jMenu1);

        jMenu4.setText("USUARIOS");

        cargar_usuarios.setText("Cargar Usuarios");
        cargar_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargar_usuariosActionPerformed(evt);
            }
        });
        jMenu4.add(cargar_usuarios);

        navbar.add(jMenu4);

        setJMenuBar(navbar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ventanaPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ventanaPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opCargarPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opCargarPeliculasActionPerformed
        //SE INSTANCIA EL NUEVO OBJETO DE LA CLASE VISTACARGARPELICULAS PARA MOSTAR
        //EN EL JFORM PRINCIPAL CON LA SIGUIENTE LINEA DE CODIGO 
        
        vistaCargarPeliculas m = new vistaCargarPeliculas();
        ventanaPrincipal.add(m); // SE ANHADE AL DESKOP PANEL QUE HABIA CREADO
        Dimension desktopSize = ventanaPrincipal.getSize();
        Dimension FrameSize = m.getSize();
        m.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        m.show();
    }//GEN-LAST:event_opCargarPeliculasActionPerformed

    private void registrar_generoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrar_generoActionPerformed
        //SE INSTANCIA EL NUEVO OBJETO DE LA CLASE VISTACARGARPELICULAS PARA MOSTAR
        //EN EL JFORM PRINCIPAL CON LA SIGUIENTE LINEA DE CODIGO 
        
        RegistrarGenero m = new RegistrarGenero();
        ventanaPrincipal.add(m); // SE ANHADE AL DESKOP PANEL QUE HABIA CREADO
        Dimension desktopSize = ventanaPrincipal.getSize();
        Dimension FrameSize = m.getSize();
        m.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        m.show();
    }//GEN-LAST:event_registrar_generoActionPerformed

    private void cargar_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargar_usuariosActionPerformed
        
        usuarios u = new usuarios();
        ventanaPrincipal.add(u);
        Dimension desktopSize = ventanaPrincipal.getSize();
        Dimension FrameSize = u.getSize();
        u.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
        u.show();
        
        // aca es
    }//GEN-LAST:event_cargar_usuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cargar_usuarios;
    private javax.swing.JLabel escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JMenuBar navbar;
    private javax.swing.JMenuItem opCargarPeliculas;
    private javax.swing.JMenuItem registrar_genero;
    public javax.swing.JDesktopPane ventanaPrincipal;
    // End of variables declaration//GEN-END:variables
}
